### ISSUE TITLE
merging todo

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#2820]
a list of things not resolved during last big merge 

- [x] lnk program cannot be indexed, unregistered directory has been confirmed, need more testing: efc01034c21a254eb8abd464541e445eb63bc590
- [ ] use using 404effd8d510293ddc6ebf010c914ff763f8b225

**Comment by bao-qian** [comment]
todo


- [x] test with vs 2019
- [x] update appveyor to 2019
- [x]  update readme for 2019 and windows api
- [ ] remove useless app packaging dll
- [ ] ps execution policy
- [ ] merge browser bookmark plugin pr


program icon related:

- [x] Failed to get thumbnail 
- [x] steam (and lots more) icon exception in first type. 
reproduce: run in debug mode, attach debugger, and type steam
workaround: click continue, type again, steam icon properly displayed. or do not use debugger.

```
 	Wox.Infrastructure.dll!Wox.Infrastructure.Logger.Log.Exception(string message = "|ImageLoader.Load|Failed to get thumbnail for C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Steam\\Steam.lnk", System.Exception e = {"Error while extracting thumbnail for C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Steam\\Steam.lnk"}) Line 135	C#
>	Wox.Infrastructure.dll!Wox.Infrastructure.Image.ImageLoader.LoadInternal(string path = "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Steam\\Steam.lnk", bool loadFullImage = false) Line 174	C#
 	Wox.Infrastructure.dll!Wox.Infrastructure.Image.ImageLoader.Load(string path = "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Steam\\Steam.lnk", bool loadFullImage = false) Line 186	C#
 	Wox.exe!Wox.ViewModel.ResultViewModel.Image.get() Line 41	C#
```
- [ ] can't find logo uri for

**Comment by enria** [comment]
你复活啦？

**Comment by bao-qian** [comment]
@enria 
复活了 

新 release
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.735

昨天已经清完了历年所有 pr，今天就可以清完所有 issue。
