### ISSUE TITLE
.NET 4.5

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#393]
.NET 3.5 seems has bugs.
- [x] In #384, Wox will crash when user type Non-Latin characters.
- [x] And .NET 3.5 also cause problems in #392.

I tried .NET 4.5 with `dotnet45` branch.
Everything seems good except the UI of selected item is not working.
It can also install plugins written in .NET 3.5 without problems, I tried youdao plugin.

Other pros:
#236 able to use quirrel.Windows for installer and auto updates
#333 able to use `Task` library

Current problems prevent to upgrade:
- [x] 1. the color of selected item is not correct.
  ![selected item](http://i.imgur.com/mJlvZYj.png)
- [x] 2. the color of mouse over item is not correct.
  ![mouse over item](http://i.imgur.com/LShBi2C.png)
- [x] 3. sometimes the icons are flickering

**Comment by luisrudge** [comment]
Hey guys.. We have to make this happen. Using .net 3.5 is very limiting on what we can do and how we can do. Not having async/await or not being able to use the latest client libraries is not good for the ecosystem. Who can I help make this happen?

**Comment by bao-qian** [comment]
Hi @luisrudge,
There is a `dotnet45` branch. You can merge master into that branch. And then fire PR into `dotnet45` branch.
Problems I noticed
- [x] 1. the color of selected item is not correct.
  ![selected item](http://i.imgur.com/mJlvZYj.png)
- [x] 2. the color of mouse over item is not correct.
  ![mouse over item](http://i.imgur.com/LShBi2C.png)
- [x] 3. sometimes the icons are flickering

3 should be fixed by my self. I need help with 1 and 2, since I don't know WPF.

**Comment by devployment** [comment]
@happlebao, just curious on how you got this mouse over item effect. Which theme are you using? For me using the default "Dark" theme does not show any over item effect.

**Comment by bao-qian** [comment]
@deployment this is a bug in dotnet45 branch using default Dark theme.

**Comment by bao-qian** [comment]
What's your os version?

**Comment by devployment** [comment]
Just to be clear. That means the over item effect should not be there at all, right? 

OS: Windows 8.1. Enterprise

Will try to fix these two issues and create a pull request.

**Comment by bao-qian** [comment]
Yes, it should be same as master branch. Thanks for help!

**Comment by lances101** [comment]
@happlebao Can you scroll through the results with arrow keys and/or tab? I built the .net 4.5 branch and it does not seem to react on my system.

**Comment by bao-qian** [comment]
@lances101 
I merged `master` into `dotet45`, check it.
It had occasionally occurred, but I can't reproduce it now.

**Comment by bao-qian** [comment]
- [x] Current master build will cause problem when running on .net 4.5 runtime. #428

**Comment by bao-qian** [comment]
@lances101 it's probably related to .net version.
Download this software：http://www.asoft.be/prod_netver.html
paste info like this to here

```
<32Bit>
2.0.50727.8669
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.6.1055.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.8669
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.6.1055.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

< Installed .NET Frameworks >
.NET FW 2.0 SP 2  (CLR:2.0)
.NET FW 3.0 SP 2  (CLR:2.0)
.NET FW 3.5 SP 1  (CLR:2.0)
.NET FW 4.6 Unknown build:394271 (CLR:4.0)
```

**Comment by luisrudge** [comment]
any updates on this?

**Comment by foobarbazmeow** [comment]
[Support Ending for the .NET Framework 4, 4.5 and 4.5.1](http://blogs.msdn.com/b/dotnet/archive/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1.aspx)

**Comment by bao-qian** [comment]
@luisrudge  sorry, no. I'm recently busy to look find a job.
@antigravity 4.5.2 is still supported.

**Comment by luisrudge** [comment]
Can you enumerate what needs to be done in order to migrate wox to the latest .net version?

**Comment by bao-qian** [comment]
@luisrudge hi, please take a look: https://github.com/Wox-launcher/Wox/issues/393#issuecomment-159347775

**Comment by luisrudge** [comment]
Ok. I'll try to help you with 1 and 2.

**Comment by bao-qian** [comment]
Thanks a lot

**Comment by bao-qian** [comment]
Update: I finally figured out how WPF handle background color for win8+, Wox will be moved to .net 4.5 soon.

**Comment by bao-qian** [comment]
Hi guys, all the problems seems resolved now. take a look of [build 1.2.662](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.662/artifacts).
Remember install .net 4.5.2+ before launch it :) .
@lances101 @luisrudge @devployment @antigravity @cH40z-Lord

**Comment by bao-qian** [comment]
@PengKISS #428 【1.2 beta2 回车和上下键选择没反应】这个问题在 [build 1.2.662](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.662/artifacts) 还存在吗？

**Comment by keichinger** [comment]
@happlebao awesome!

I've noticed a few issues after the first minutes of testing it on my Windows 10 1511 Build 11082 x64 (Insider Preview) machine:
- When copying Wox in an UAC-required location such as `%ProgramFiles(x86)%´ and then running it _without_ admin permissions will bring up the custom Exception dialog, though there is no chance to submit or review it since it's closed automatically after less than a second. I haven't looked into it yet what's causing this but I've got a strong feeling that it is caused due to insufficient permissions for creating directories upon first launch.
- No plugins were installed by default even though each directory under `\Plugins` has content.
- Probably related to ^: Searching for anything (no matter if it's just `settings` or anything else) won't bring up any search results and all I see is the progress bar under the search input

**Comment by bao-qian** [comment]
@cH40z-Lord this is not .net 4.5 issue, this is deployment issue, track using #360.

1: yeah, please put it under %userprofile% for now.
2+3: this is a win10 specific issue, please take a look of https://github.com/Wox-launcher/Wox/issues/279#issuecomment-140522847 for workaround. This is will be fixed soon since .net 4.5 enable us to use [Squirrel](https://github.com/squirrel/squirrel.windows) as installer.

**Comment by lances101** [comment]
@happlebao So far the `.net 4.5` branch seems to run without any problems on the VM I'm using. I will report if I find any issues.

**Comment by bao-qian** [comment]
@lances101 can you scroll now? see https://github.com/Wox-launcher/Wox/issues/393#issuecomment-164225509

**Comment by lances101** [comment]
@happlebao yes, so far all the times I tried to scroll through the results with the keyboard - it scrolled without any problems

**Comment by luisrudge** [comment]
this build is working great for me too! When can we expect the new version to ship? I want to build some plugins :)

**Comment by bao-qian** [comment]
The new build will be shipped before Chinese spring new year after I create a installer. You can checkout master and build it now.

**Comment by luisrudge** [comment]
So, February 8th?

**Comment by bao-qian** [comment]
Yeah :)

**Comment by luisrudge** [comment]
Nice! I want it to be available to everyone, so I can ship .net 4.5 plugins :)

**Comment by bao-qian** [comment]
You can build it now and publish it after that time. You know, a good plugin needs time to build and test.

**Comment by luisrudge** [comment]
Yep! That's exactly what I'll do!
