### ISSUE TITLE
Refactoring Hotkey

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#459]
- [x] Currently there are four ways: `System.Windows.Input`, `LowLevelKeyboardProc` and `NHotkey`, [InputSimulator](https://github.com/Wox-launcher/Wox/commit/8644fb66c08d276fa6fb1e20c07befeea3bff775) used to support shortcut, it should be unified.
- [x] Remove redundant code introduced in PR #494 :
  - [x] https://github.com/LingForCC/Wox/commit/c0edaeba6bd4e5d1902b66777ab72dc2f0185564#commitcomment-16197708
  - [x] https://github.com/LingForCC/Wox/commit/4ba5602e4cb59a16a8c35fe6c1c8e381630194f5#commitcomment-16197921
- [x] `GlobalKeyboardEvent` in `IPublicAPI` should be removed. The only place to set hotkey should be `Settings.xaml`
- [x] `BackKeyDownEvent` in `IPublicAPI` should also be removed?
- [x] two layer: 
  1. `System.Windows.Input` for hotkey when Wox is focused.
  2. `LowLevelKeyboardProc` for all global hotkey

Related issue
- [ ] Customized hotkey:
  - [x] #460 
  - [x] #238
- [ ] Double tap
  - [ ] #346 double tap
- [ ] modifier keys + non modifier key
  - [ ] #984 win hook randommly not working
  - [x] #687 Ctrl+space
  - [x] #660 
  - [x] #552 
  - [x] #430
  - [x] #286 Win + ~ (buggy)
  - [x] #542 win+r
  - [x] #310 win
  - [x] #194
- [ ] other:
  - [ ] #111 keep open??
  - [ ] #1306 don't trigger capslock
  - [ ] #1024 

ideally there should be one solution
1. have one single code base, not scattering around.
2. can solve 90% of the existing hotkey issue.
3. works on win7/8/10, win10 introduce more restriction
4. plugin should not implement there own hotkey logic

**Comment by bao-qian** [comment]
ref:
https://gist.github.com/Stasonix/3181083
https://blogs.msdn.microsoft.com/alejacma/2010/10/14/global-hooks-getting-lost-on-windows-7/
http://stackoverflow.com/questions/27181125/how-to-hook-win-tab-using-lowlevelkeyboardhook
https://msdn.microsoft.com/en-us/library/windows/desktop/ms644985(v=vs.85).aspx

**Comment by bao-qian** [comment]
currently `GlobalKeyboardEvent` always returns true in my machien, which cause sometimes win+r is not intercept correctly... 
but it returns correctly in other machines #690 
strange....

<del> https://github.com/Wox-launcher/Wox.Plugin.Switcheroo/issues/6 may also releated </del>

**Comment by bao-qian** [comment]
`LowLevelKeyboardProc`:
- [ ] Win key hotkey will trigger windows start menu if you release win key (instead of non modifier key ) first
1. if we ignore key up event like [1.3.105], then it will cause https://github.com/Wox-launcher/Wox.Plugin.Switcheroo/issues/6#issuecomment-222382709
2. this also happens on alt key for firefox as reported here 
   https://github.com/Wox-launcher/Wox/issues/707#issuecomment-222361380

if 2 is a mistake, could we just ignore win key up event?

**Comment by bao-qian** [comment]
`LowLevelKeyboardProc`:
-  [x] when task manager is focused, hotkey won't be triggered. 

this could be solved by use run as administrator
http://stackoverflow.com/questions/27335011/some-windows-in-windows-8-prevent-my-low-level-keyboard-hook-from-working
- [ ] or could we use it if we sign the code?

e.g. 
win+r won't works when task manager is focused for 1.3.67

**Comment by jhdxr** [comment]
I suggest reverting commit eeb8310 , as it introduced so many bugs without fixing any issue.
btw, I'm working on #703 , I have found the reason, and I'm trying to find a elegant solution

**Comment by bao-qian** [comment]
the solution in commit  eeb8310 is the only way to handle all kinds of hotkeys, I can't find other ways...

**Comment by bao-qian** [comment]
> I'm working on #703 , I have found the reason

what's the reason?

**Comment by jhdxr** [comment]
I'm not proficient in the way handle hotkeys in windows, but for me the way in version 1.3.100 works quite well, except #703 ( I'm close to fix this issue), while I didn't find any advantages (any case that 103 can handle but 100 cannot) ojf the way to handle hotkeys in 1.3.103.

**Comment by bao-qian** [comment]
advantage:
1 you can't use win key as wox hotkey
2 #346 wants to double tap one of the modifier keys... (not working now, but possible with current solution)

> trigger时不光通过唤起wox后输入关键词，还能直接通过快捷键唤起（例如现在的cmd插件支持win+R。再举一个场景，这个功能配合一些词典类的plugin，就能够取代一些字典软件了）

3 ability to support this feature you mentioned

**Comment by jhdxr** [comment]
well, then we have no choice but fix these bugs step by step...

**Comment by bao-qian** [comment]
@jhdxr 试一下 114？
1. win 键？
2. firefox 中用 alt space ？
https://ci.appveyor.com/project/happlebao/wox/build/1.3.114

**Comment by bao-qian** [comment]
1. if we want to just use `LowLevelKeyboardProc`, then #706 won't be fixed even we use black magic code like `AttachThreadInput` (in win10)
2. if we switch back to `NHotkey` which use `RegisterHotkey`. then #706 won't happen
   1. we need to use `LowLevelKeyboardProc` as a fallback method to handle win key
   2. could we use `InputSimulator` to send <kbd>alt+space</kbd> to get focus instead of call focus method directly? no, `InputSimulator` use virtual key, so wox won't get focus too.

**Comment by bao-qian** [comment]
there are so many code related, we need make an small app test ideas instead of refactoring wox directly....

**Comment by happlebao** [comment]
Will win+r works when task manager is focused for 1.3.67?

**Comment by bao-qian** [comment]
how to disable registered hotkey
http://superuser.com/questions/129191/is-there-any-way-to-disable-certain-keyboard-shortcuts-in-windows-7

disable alt+tab

<del>[HKEY_CURRENT_USER\Control Panel\Desktop]
"CoolSwitch"="0"</del>
- [ ] 
  if we could disable these hotkey programmatically by using registry,
  could we reuse these disabled hotkey then just use registerhotkey?
  instead of use force use lowlevelkeyboardproc.

**Comment by jhovgaard** [comment]
👍 for this.

**Comment by Stanzilla** [comment]
Win+Space would be nice to have

**Comment by vantm** [comment]
I suggest using hotkey <kbd>ctrl + enter</kbd> to run app as administrator.
