### ISSUE TITLE
Buggy plugins

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#590]
following plugins are not compatible with prerelease version of 
- [x] Wox.Plugin.BrowserBookmark 1.0.0 #589 #689 #709 
- [x] Wox.Switcheroo  1.0.6 fixed
- [x] Wox.Plugin.ClipboardManager 1.1.0 #342 #414 #581 （unicode has been removed)
- [x] Wox.Plugin.Youdao 
  - [x] #639 
  - [x] #663
- [x] Wox.Plugin.Simpleclock 
  - [x]  #688 use storage
  - [x] #685 use command line arguments?

**Comment by bao-qian** [comment]
thanks @lances101 to fix these plugins
